on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  base-image-build:
    name: Rust dev image build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ruimo-rust-dev
    steps:
      - name: "Build"
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
